from app.extensions import db
from datetime import datetime
import uuid
import json

class IntelligenceSignal(db.Model):
    """
    Represents an operational signal or anomaly (e.g., DEMAND_SURGE, INVENTORY_ANOMALY).
    """
    __tablename__ = 'intelligence_signals'

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    type = db.Column(db.String(50), nullable=False) # e.g. DEMAND_ANOMALY, INVENTORY_ANOMALY
    severity = db.Column(db.String(20), nullable=False, default='LOW') # LOW, MEDIUM, HIGH, CRITICAL
    message = db.Column(db.String(255), nullable=False)
    context_data = db.Column(db.Text, nullable=True) # JSON payload with context (e.g., product_id, current_velocity)
    canteen_id = db.Column(db.Integer, nullable=True) # if multi-canteen
    stall_id = db.Column(db.Integer, db.ForeignKey('stalls.id'), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    resolved_at = db.Column(db.DateTime, nullable=True)
    status = db.Column(db.String(20), nullable=False, default='OPEN') # OPEN, ACKNOWLEDGED, RESOLVED

    def get_context(self):
        return json.loads(self.context_data) if self.context_data else {}


class Recommendation(db.Model):
    """
    Prescriptive Intelligence: Actionable recommendation generated by the engine.
    """
    __tablename__ = 'recommendations'

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    type = db.Column(db.String(50), nullable=False) # e.g., REORDER, MOVE_STOCK, ADJUST_STAFF
    priority = db.Column(db.String(20), nullable=False, default='MEDIUM')
    reason = db.Column(db.Text, nullable=False)
    confidence = db.Column(db.Float, nullable=True) # e.g., 0.91 (91%)
    suggested_action = db.Column(db.Text, nullable=False) # JSON payload of what to do
    
    # Target entities
    product_id = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=True)
    stall_id = db.Column(db.Integer, db.ForeignKey('stalls.id'), nullable=True)
    
    status = db.Column(db.String(20), nullable=False, default='GENERATED') # GENERATED, REVIEWED, APPROVED, REJECTED, MODIFIED, EXECUTED, EXPIRED
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    expires_at = db.Column(db.DateTime, nullable=True)
    
    # Audit trail reference
    reviewed_by = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    reviewed_at = db.Column(db.DateTime, nullable=True)
    
    def get_action(self):
        return json.loads(self.suggested_action) if self.suggested_action else {}


class RecommendationAudit(db.Model):
    """
    Tracks feedback loop and outcomes of recommendations.
    """
    __tablename__ = 'recommendation_audits'

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    recommendation_id = db.Column(db.String(36), db.ForeignKey('recommendations.id'), nullable=False)
    decision = db.Column(db.String(20), nullable=False) # APPROVED, REJECTED, MODIFIED
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    notes = db.Column(db.Text, nullable=True)
    execution_result = db.Column(db.Text, nullable=True) # Text or JSON of what actually happened
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
